_target_: src.models.timm_module.TIMMLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: timm.create_model
  model_name: resnet18
  pretrained: True
  num_classes: 10
  #input_size: 784
  #lin1_size: 64
  #lin2_size: 128
  #lin3_size: 64
  #output_size: 10
